#!/bin/sh
# stale bytecode from a previously installed version (the feed ships
# compiled bytecode) must never shadow the fixed sources
PLUGIN_DIR=/usr/lib/enigma2/python/Plugins/Extensions/DreamPlex
find "$PLUGIN_DIR" -name "*.pyc" -exec rm -f {} + 2>/dev/null
find "$PLUGIN_DIR" -name "*.pyo" -exec rm -f {} + 2>/dev/null
find "$PLUGIN_DIR" -type d -name "__pycache__" -exec rm -rf {} + 2>/dev/null
echo ''
echo '#####################################################'
echo '# DreamPlex (modern PMS fork) installed.            #'
echo '# Restart the enigma2 GUI to activate the plugin.   #'
echo '#####################################################'
echo ''
exit 0
